[workspace]
members = [".", "entity", "migration"]

[package]
name = "ip-msg"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ip_msg_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
uuid = { version = "*", features = ["v4"] }


[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tokio = { workspace = true }
uuid = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sea-orm = { version = "1.1.0", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
] }
dotenv_codegen = "0.15.0"
anyhow = "1.0.95"
log = "0.4.25"
