[package]
name = "entity"
description = "SeaORM generated entites for ip-msg"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
